/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter Variable', 'Segoe UI', 'system-ui', 'sans-serif'],
        mono: ['Inter Variable', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: '#6366f1',
        'primary-container': '#3730a3',
        secondary: '#8b5cf6',
        'secondary-container': '#5b21b6',
        tertiary: '#10b981',
        'tertiary-container': '#065f46',
        error: '#ef4444',
        'error-container': '#991b1b',
        surface: '#090a0f',
        'surface-bright': '#27272a',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#090a0f',
        'surface-container': '#18181b',
        'surface-container-high': '#27272a',
        'surface-container-highest': '#3f3f46',
        'surface-variant': '#27272a',
        'on-surface': '#f4f4f5',
        'on-surface-variant': '#a1a1aa',
        outline: '#3f3f46',
        'outline-variant': '#27272a',
        'amber-accent': '#f59e0b',
        'emerald-accent': '#10b981',
        'crimson-accent': '#e11d48',
        'card-border': '#27272a',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'sidebar-w': '16rem',
      },
      fontSize: {
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.5rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'title-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '500' }],
        'title-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '500' }],
        'display-sm': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
        'label-caps': ['0.625rem', { lineHeight: '0.75rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-metric': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.015em', fontWeight: '500' }],
      }
    },
  },
  plugins: [],
}
